name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: "setup go"
      uses: actions/setup-go@v3
      with:
        cache: true
        go-version-file: 'go.mod'

    - name: build
      run: make zip

    - name: "create release"
      uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        artifacts: "release/*.zip"
        draft: true
        generateReleaseNotes: true
